#ejercicio1
número1 = input("Introduce un número: ")
print(número1)
print(type(número1))
print("\n")
número2 = int(input("Introduce otro número: "))
print(número2)
print(type(número2))
print("\n")
número3 = float(input("Introduce otro número: "))
print(número3)
print(type(número3))